const User = require('./user.model');
const Product = require('./product.model');
const Category = require('./category.model');
const Review = require('./review.model');
const Cart = require('./cart.model');
const Order = require('./order.model');
const Token = require('./token.model');
const Discount = require('./discount.model');
const Favorite = require('./favorite.model');
const Color = require('./color.model');
const Size = require('./size.model');
const Terms = require('./terms_model')
const Privacy = require('./privacy_model')
const Notify = require('./notification.model')
const Banner = require('./banner_model');
const Support = require('./support_model');
const Help = require('./helpandSupport')
module.exports = { User, Product, Category, Review, Cart, Order, Token, Discount, Favorite, Color, Size, Terms, Privacy, Notify, Banner, Help, Support };
